services:
  # Servicio de API Gateway
  - type: web
    name: gateway-service
    repo: https://github.com/EmerIlesS/Api-Gateway.git
    plan: starter
    region: ohio
    branch: main
    env: node
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: AUTH_SERVICE_URL
        value: https://ms-auth-java-service.onrender.com/graphql
      - key: PRODUCTS_SERVICE_URL
        value: https://ms-products-orders-service.onrender.com/graphql
    buildCommand: npm install && npm run build
    startCommand: npm start
